import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { authOptions } from './lib/auth'

import SessionProvider from './components/SessionProvider'
import { Toaster } from './components/ui/toaster'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  )
}
